[manifest]
name = "hyprsbar"
version = "0.1.0"
authors = ["ryugen-io"]
description = "Generate hyprsbar.conf from hyprsink theme"
license = "MIT"

[[targets]]
target = "~/.config/hypr/hyprs/bar.conf"
content = '''
# hypr metadata
# type = bar
# generated by hyprsink template: hyprsbar

[window]
height = 30
anchor = "top"
monitor = ""
scale_font = true
pixel_font = false
font_base_size = 10
min_padding = 2

[style]
bg = "{{ colors.bg }}"
fg = "{{ colors.fg }}"
window_bg = "{{ colors.bg }}"
popup_bg = "{{ colors.bg }}"
accent = "{{ colors.primary }}"
primary = "{{ colors.primary }}"
secondary = "{{ colors.secondary }}"
success = "{{ colors.success }}"
error = "{{ colors.error }}"
font = "{{ fonts.mono }}"

[style.colors]
header_fg = "{{ colors.primary }}"
mono_fg = "{{ colors.fg }}"
panel_bg = "{{ colors.black }}"
panel_border = "{{ colors.secondary }}"
glass_bg = "{{ colors.selection_bg }}"
error_bg = "{{ colors.error }}"
dimmed = "{{ colors.bright_black }}"

[layout]
modules_left = []
modules_center = []
modules_right = []
left = 33
center = 34
right = 33
strategy = "grid"
padding = 1

[layout.labels]
bar_startup = "hyprsbar starting..."
bar_running = "daemon running (pid: {pid})"
bar_stale = "stale pid file cleaned"
bar_start = "daemon started (pid: {pid})"
bar_stop = "daemon terminated (pid: {pid})"
bar_not_found = "no daemon found"
bar_restart = "restarting daemon..."
bar_term_error = "no compatible terminal found for debug"
bar_autostart_enabled = "Hyprland autostart enabled"
bar_autostart_disabled = "Hyprland autostart disabled"
bar_sigterm = "Received SIGTERM (Toggle), shutting down..."
bar_sigint = "Received SIGINT, shutting down..."
bar_debug_started = "debug mode started"
bar_plugins_header = "Installed Plugins:"
bar_plugin_status_enabled = "enabled"
bar_plugin_status_disabled = "disabled"
bar_plugin_entry = "- {name}: {status} ({path})"
bar_plugin_meta = "  v{version} by {author}"
bar_plugin_desc = "  {description}"
widget_loaded = "Loaded Dish: {0} (Type: {1})"

[logging]
level = "info"
debug_filter = "info,hyprsbar=debug"

[popup]
offset_x = 0
offset_y = 0
'''

[hooks]
